package com.bluestacks.os;

/**
  * Functions ordering here should not be altered,
  * If new functions are to added, they should be appended.
  * This order directly corresponds to ordering in /frameworks/native/include/binder/IBstFilterAppsService.h
  * If order of functions is altered here, similar changes should be done in /framework/native.
  */
interface IBstFilterAppsService
{
    boolean isSmallScreenApp(String pkgName);
    boolean forceArmInstall(String pkgName);
    boolean forceX86Install(String pkgName);
    boolean isWhiteListed(String pkgName);
    boolean isBlackListed(String pkg, String version);
    boolean isSoftKeyboardRequired(String pkg, String activity);
    String getSoftKeyboardModifier(String pkg);
    boolean isMarketRequired(String pkgName);
    boolean isHeadsetRequired(String pkgName);
    boolean isPortraitDisabled(String pkgName);
    String getCustomDpi(String pkgName);
    boolean isGlv1notimpApp(String pkgName);
    boolean isPvrtcApp(String pkgName);
    boolean isXarchApp(int uid);
    boolean isS3tcApp(String pkgName);
    boolean isClearInstallApp(String pkgName);
    boolean isScreenOrientationFixed(String callingPkgName,String currentPkgName);
    int isCameraRotationRequired(String pkgName);
    boolean forceLandscapeOrientationIfUnspecified(String pkgName);
    String getGlRenderer(String pkgName);
    String getGlVendor(String pkgName);
    boolean isGL3App(String pkgName);
    String isLoadLibHackReqd(int uid);
    boolean isGL3Disabled(String pkgName);
    boolean isZeroMappedPageReqd(int uid);
    boolean isModifysdPathReqd(String pkgName);
    boolean isAGAGL3Disabled(String pkgName);
    boolean isPGAGL3Disabled(String pkgName);
    boolean isShowOrigCpuinfoArmApp(int uid);
    boolean isAstcApp(String pkgName);
    boolean isPatchRelocApp(int uid);
    String getPgaGlVersion(String pkgName);
    String getAgaGlVersion(String pkgName);
    boolean isHardwareAstcDisabledApp(String pkgName);
    boolean isXArmApp(String pkgName);
    String getMemorySize(int uid);
    boolean isIMEDisabled(String pkgName, String activity);
    boolean isForceVibrate(String pkgName);
    boolean isHideBstActivityInfo(String pkgName);
    boolean isArmApp(int uid);
    boolean isXCpuAbi(String pkgName);
    boolean isModifyDisplayRotationApp(String pkgName);
    boolean isBluestacksPartnerApp(String pkgName);
    String getAccelerometerSetting(String pkgName);
    List<String> getAccelerometerList();
    List<String> getHeadSetList();
    String getInstallerPkg(String pkg);
    String getBrowserUrl();
    void updateAbiEntry(int uid, String pkgName, int action);
    String getConfigInfoForPackage(String pkgName);
    String getBlackListAction(String pkg);
    int getForceAbiInstallMode(String pkgName);
    boolean isForcedDexoptWithInstallFlag(String pkgName);
    boolean isAppUsingOldHoudini(int uid);
    String getAdditionalGlExtensions(String pkg);
    boolean areInputDevicesExposed(String pkgName);
    boolean isShowArmAbiListApp(int uid);
    boolean isIgnoreLargeHeapApp(String pkgName);
    boolean isClearCodeCacheApp(int uid);
    boolean isForcedInputDisabledApp(String pkgName);
    boolean isImageDetectionEnabled(String pkgName);
    int getHeapGrowthLimitSize(String pkgName);
    boolean isHideProcMapsApp(String pkgName);
    boolean isEnableNativeGamePad(String pkgName);
    boolean isPreloadBstHookLibraryApp(String pkgName);
    boolean isIl2cppApp(int uid);
    void updateIl2cppPkgs(String pkgName);
    boolean isSuppressedNotificationApp(String pkgName);
    boolean isMacrosDisabledApp(String pkgName);
    boolean showFeedbackPopup(String pkgName);
    float ffmpegConfidenceForApp(String pkgName);
    boolean isAppUsingSwappy(int uid);
    String getMouseCursorStyle(String pkgName);
    int getCameraSensorRotation(String pkgName);
    boolean isUE4GLFlushApp(String pkgName);
    boolean isGetNowggAccountsListApp(int uid);
    boolean isGoogleSignInRequired(String pkgName);
    String getMouseAction(String pkgName, String activity);
    String isVulkanRequired(String pkgName);
    boolean isForceKillApp(String pkgName);
    boolean isFixedDisplayRotationApp(String pkgName);
    String getGameDefaultSetting(String pkgName);
    boolean isHppEnabled(String pkgName);
    boolean isHotFixApp(String pkgName);
    boolean isGLInvalidateFramebufferFilterApp(String pkgName);
    int getUnityFlickerPatchRequired(String pkgName);
    String getDefaultProfile(String pkgName);
    int getXperfMode(int uid);
    boolean isIntelGLDispatchComputeFlushApp(String pkgName);
    int getCameraInitRotation(String pkgName);
    boolean isDhdg(int uid);
    boolean isGlNativeSyncDisabled(String pkgName);
    boolean isAngleDisabled(String pkgName);
    boolean isFbScreenLockApp(String pkgName);
    boolean isOneStorePay(String pkgName);
    boolean isGLProgramBinaryApp(String pkgName);
    boolean isGLUnmapBufferPerfApp(String pkgName);
    String getGLShaderWorkaround(String pkgName);
    boolean isDrmEnabled(String pkgName);
    boolean isTexTargetCheckDisabled(String pkgName);
    int getFixedSurfaceRotationRequired(String pkgName);
    String getIapSetting(String pkgName);
    boolean isGlMapBufferRangeHost(String pkgName);
    boolean isIgnoreSyncTimeout(String pkgName);
    boolean isGLVBOCacheDisableApp(String pkgName);
    boolean isBlockEditWhenComposing(String pkgName);
    String getGLHostInfo(String pkgName);
    String getGLExtensionsIgnore(String pkgName);
    boolean isEGLSurfaceIgnore(String pkgName);
    boolean isHardKeyBoard(String pkgName);
    boolean isIntelAutoGLFlushApp(String pkgName);
    boolean isRotateDisabled(String pkgName);
    boolean isUnreal5App(String pkgName);
    boolean isUE5PBDisabled(String pkgName);
    boolean isBptcApp(String pkgName);
    boolean isExtractNativeLibs(String pkgName);
    boolean isEtherNetType(String pkgName);
    String getVkHostInfo(String pkgName);
    String getVKDeviceExtIgnore(String pkgName);
    boolean isDefaultXYDpi(String pkgName);
    int getPScoreAbove(String pkgName);
    boolean isMapBufRangeReadOnceEnabled(String pkgName);
    boolean isFbCompleteCheckDisabled(String pkgName);
}
