package com.bluestacks.os;

/** @hide */
interface IBstHostCallService {
    int initImeStatus(String imeName);
    int initInputDebuggingStatus(boolean showTouches, boolean showPointerLocation);
	int syncInstalledApps(String jsonData);
    int onOrientationChange(int orientation);
    int onImeChange(String imeName);
    int onTextEditModeChange(boolean isTextEditMode);
    int onActivityDisplayed(String pkg, String activity, String callingPackage);
    int exportFiles(String folder);
    int startImportFiles(String type, boolean isMultipleAllowed);
    int startExportFiles();
    int setClipboardText(String text);
    int onVolumeChanged(boolean mute, int volume);
    int onGoogleLoginCompleted(String emailId);
    int onBluestacksLoginCompleted(String emailId);
    int setAppConfigDbParams(String pkg, boolean macrosDisabled, boolean showFeedbackPopup, String mouseCursorStyle, boolean nativeGamepad);
    int googleAccountListUpdated(String emailId, int action);
    boolean isAppLaunchAllowed(String pkg, boolean isFromRecentApps);
    int setGoogleAdId(String googleAdId);
    int onCursorLocationChanged(int x, int y);
    int onLocaleChanged(String locale);
    int onAppInstalled(String jsonData);
    int onAppUninstalled(String pkg);
    int onScreenshotSaved(String fileName);
    int createDesktopShortcut(String pkg);
    int importFilesCompleted(int status, String folder);
    int openUrl(String url);
    int initVolume(boolean mute, int volume, int maxVolume);
    int onAppNotificationReceived(String notificationJson);
    int launchBsx();
    int setUsageStatsUpdateInterval(int secs);
    int onVibrate(int duration, String pkg);
    int onConsoleModeStateChanged(boolean consoleModeState);
    int affiliateTrackingCompleted(String pkg);
    int onNowggAccountAdded(String accountInfoJson);
    int onNowggAccountRemoved(String accountName);
    int onGetNowggAccount(String accountInfoJson);
    int onSetMouseAction(String pkg, String activity, String action);
    int onInstallApkCompleted(int status, String apkFileName, String errorString, String attemptId, String packageName);
    int onUpdateQuestRules(String rules);
    int onDifferentImagePkgClicked(String pkg);
    int onWalletMessage(String content);
    int onCustomAppOrientationCompleted(String pkg);
    int screenRecordingStarted(boolean started, boolean showTaps, int audioSource);
    int handleCustomIap(String actionType, String actionData);
    int onAdsInfoClick();
    int removeBootLoadingScreen(boolean onAdShown);
    int interstitialAdCompleted(String source, String action);
    int onNowbuxUpdated();
    int commonCommand(int code, String name, String data);
    int onIAPCompleted(String source, String data);
    int unzipFile(String fileName, String attemptId, String source, String pkgName);
    int allowInstallApkGameCenter(String pkg);
    int onNowggSigninClicked(String pkg, String actionType);
    int onUiDumpCompleted(String uiDump);
}
